name: Terraform destroy

on:
  workflow_dispatch:

jobs:
  destroy:
    name: "Terraform-Destroy"
    runs-on: ubuntu-latest
    env:
      working-directory: ./
      name: tear-test-bucket2
      owner: shivam.bembey@cloudeq.com

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id :  ${{ secrets.ACCESS_KEY}}
          aws-secret-access-key : ${{ secrets.SECRET_ACCESS_KEY }}
          aws-session-token :     ${{ secrets.SESSION_TOKEN }}
          aws-region : us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Destroying infrastructure with Terraform
        working-directory: ${{env.working-directory}}
        run: |
          terraform init
          terraform destroy -var name="${{env.name}}" -var owner="${{env.owner}}"  -auto-approve
